# Generated by Django 6.0.4 on 2026-04-15 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='restaurants.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
