# Generated by Django 6.0.3 on 2026-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('WAITER', 'Waiter'), ('ADMIN', 'Admin'), ('KITCHEN', 'Kitchen'), ('CASHIER', 'Cashier')], max_length=20),
        ),
    ]
