# Generated by Django 6.0.4 on 2026-06-15 11:51

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_guest'),
        ('restaurants', '0004_restaurant_branding'),
        ('table_sessions', '0002_sessionguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_token', models.CharField(db_index=True, default=apps.orders.models.generate_table_request_token, max_length=64, unique=True)),
                ('request_type', models.CharField(choices=[('CALL_WAITER', 'Call waiter'), ('REQUEST_BILL', 'Request bill'), ('NEED_HELP', 'Need help')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_requests', to='table_sessions.sessionguest')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_table_requests', to='restaurants.staff')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_requests', to='restaurants.restaurant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_requests', to='table_sessions.tablesession')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_requests', to='restaurants.table')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='orders_tabl_restaur_ebeda1_idx'), models.Index(fields=['session', 'status'], name='orders_tabl_session_d92333_idx')],
            },
        ),
    ]
