# Generated by Django 6.0.4 on 2026-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_menuitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['restaurant_id', 'sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['restaurant_id', 'category_id', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
